{
	"data": "ENC[AES256_GCM,data:ZLBqftV9fK7vJSjf8Bk7F+YrOaOkhUq7LESIT+DyFdd2HzTkeoL4ZYFQp+nZ8P4UVQFXs30fdfzqn23K+/Vxlh+vkf/GkUmrdMV4MRFqlXlnX9MOtVxPLsI9NzHHNFHm3xs6nWzVjkCT6Q2R5GFZalIAIiYWZLchE+Ust1nvf5wg1+i1fGphpxPlrOsjlQNJ4kk8bOu8Jfc3J+R0enD/4T8ABVJa0yLo0IeA7AAvmhg4kAhlGP85u4hWdOwPI8XVY3fLHy6RHGNdP4GTSfF2rXLcslaWSuEueEeh0SCSXTSfPiH5DjQjeBAngkCdS87jveNiZZcfRHM4jBwyqB8k/xPlvW9fO3bL/kj0O195L6GOBfdC6K/QLO6Dg2kP+POFEn0kOqsvXpDEOC79Ate+qKsHIzNo96GaQPU2hxAPpBRvurk+QUIcihQ+2KKEpjAYdmb+1SXGMKnVpmjxgVa81/iCxeBCiABLfn0Oy/dITwg=,iv:1n0v+gtb9655PztBPe03E6T8gpPOlzknNiZJv12itNI=,tag:542cOcdNfeS88je3BOlyWg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR0xCV0IyT295TWlIZ2Rp\nbFhkSS9jY2lLQ2hUbVZsekJjY0s4OGlxSW4wCjRpU1I1QzBYWkpPdTNXT3VKTUpR\na0VKdlJQcW5OVDRrSkN5STdaSGJyWUkKLS0tIE5qRFQvSjJUZ1p3aFZVY292blNt\nSnB5OG1xNk1LL1pIZ3ltR0orY0pEQUEKydLiA7rtRLCl0y+gp0EgpdlAHKFyGcCS\nbcFd+C8sGmuES/1Wqc47EF4ZENM1qJoCe1K+awnSxvsJ8gjxjIk90A==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-12T17:07:02Z",
		"mac": "ENC[AES256_GCM,data:NNWdGCFKiTlkdkQAra8LaLDGqbuEuXFprWBzRbxMrxPZUESLSPEMqCOC9ZqHBo405CzImjwPG9kocclLtNao3ejRDTtUXh4fz86QfbcMXyb4OUMrITSKZR/1eT/wgEysAUik2l24doDEkaJMXVRrS8j50LsqzkObcpdQpPZDP0U=,iv:qne0t1EuBQ6U0DP+9YjPs1eIL8v5appx1QUgXeqCiuw=,tag:3cDxNSAVrnqLVm5L0E7XeQ==,type:str]",
		"version": "3.13.3"
	}
}
