{
	"data": "ENC[AES256_GCM,data:xlDSBcE9DCGhd7zRNNYWtQ70KSxo7ChR/gDooqJsbVnD5QQ8kF+5io/4iUD2KXb7gVgSEpPmSLU73AGrfytrL0mkUFexLClTm6YMfhPXM96EjJVMxf01ldnU+dRcyiWIKRjU+IRJFOzTTi8ACUnKPlylxuPmbvSJQbAVf30RMyJsJe3tGBf+uMWSrAEMmeS7KA1OZgirYzjvbpoE1NbFLmmgCG31XsP5Aw==,iv:7+clB6aR3hOOVVl2qENdsrLmtXUpqceNmRyUXJjjra0=,tag:C5+KP92Q3sw4s0NreYQ9Mw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QXRmNjZsN1o0bUJ4YTRi\nZDBlMC9FR1RidHNyWDJSYWpPYWMvSVdHY0RrCkZER01ab054aGRGZmFIYkl3V0NH\namNrNmxJOGhpT0Z4WFN5Y0pWOHVYbzgKLS0tIGg1eXVocSs2K2Q5QjhiUmorUCsr\nTWNMYkp2MEhxY1hmd081K0s3blVtK0EKh2p/gUADwjaDBQ6PPA1SWY/aTNELRZcM\nrJf2sV2EiyCqbfp/1RByj/pgE8hGnXLgMAs01aFKFXxyKuVDz+o72g==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-12T16:17:13Z",
		"mac": "ENC[AES256_GCM,data:IpIqygifJZNnjE2eGsCO68MSJYOGloWovXU1ErPNCOX0qis6O5ySTlNI7ltGIPIbhs12GnnndOWVNTKlWkK63MzOqjNlZUR//pN9Lq2XY+eZ1MliIkL/zvt2BSOIyoPAoZfggXBwTKNhT60IzSBbu+sgcTppA4oN5vILdRWp0rQ=,iv:p7vEXgszNRfzvSlCGb9pCaps76ca4F31MBEisgeouf4=,tag:HnDEaglupY/ZJ/UCycRc1g==,type:str]",
		"version": "3.13.3"
	}
}
