{
	"data": "ENC[AES256_GCM,data:zfvqOj+QgZ8imtPmbg25u2sOefYOTQB2tCGPmEM7fNJoC+v4yTQaZGK20lPwnxjX81k09kQZqrNrKsoFVNrlxEsXqatRIuGpPQgLnEzjoN7Q3CC8W87iAy/AdP1wQVAkAI3oL0EwyYrHs0p51nqAikyrJz4WVeSMY1QwERLXbFwkDaihCqAeQHYW0fKc/xswv5chFudD+Eutg5RlEQ4ne50E7tB0CqcOwUWPzQMUXwg4KFZayKq3hLwJLIbGubeWiHgwngElmq8PZjM+AN9fGFhiIu6Zu9zqem1L/EFvv4MCfV67z6KjANKZku8yvGlMcXhYEJFSNrskhhZBz6X4mx2ez9D0v4lrSor+XskTxbYH49FRZIFIsoVFXbpuNwUjMeGbqoQ8Bx6UvlgYqmNAPaMZR26It36OfK5YwMuqg1PXAg4a3trMFzJK30Q6G3qcC8wKGQQkAllhUEFNKKZT2ljE5JSgtCKAhB3+SegVvBB7sFVzZ31hybb2BKOK9xAuAlyi8IU/iJTeIhiyed2Bbblzf6BCxIcmUh6l8YaaB5F59A+LZdfxNR079C5AkbIn80Jq55kpY52QX5+Jbw==,iv:/DNhgvyc6HTHPAaRz0g88eFY+aIwesFtrIWhO6N6+QE=,tag:z2aDOxLiGKKuyFGZPwYokA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVExxbUF3N2taRzdvaSs5\nNGJ4QlRGOGxDQi8vMmVZZ2MrOVM1MjZBbnljClA0aDRFWXo2YXN1ZFpBb09wVi9O\nY0t5MmQxSmZTL3BEZVkyQ2Y5RlB0T1UKLS0tIHBHc0U5cG9raEdGd1labWNidE5Z\nMHNHSjh5L1JCUk9lL0FpL25KMTJuMHcKg+Glab760L6cmDVWdPck+4L/kzzGVKzJ\n64sCpFVGYw2U30AmdxPTmzNQRz1PvnPjMMbXb5WpI2YGSVhrrEwzzw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-17T21:42:15Z",
		"mac": "ENC[AES256_GCM,data:aG+Q9Kt6eUlm66lrahuII85vhYyqDQg+lYTiKO1aOLtxGobfSE+BOJUl+4FXAuKgUD85rABJMiFNLGU+z5pZY6huJK9VnRgMBvdCAITkeJWv9Tm/4qhWCwMBBF62S7wv8bRSZkNBJZWPCU0CvZImkBvesa8DHa4psmnqDWhgjFc=,iv:BrAQfyv8/zgydfS2sEjSlDAl0LBIdL+cU59yu2D9wVI=,tag:bIMeKNiPt67zACflUEoBOg==,type:str]",
		"version": "3.13.3"
	}
}
