{
	"data": "ENC[AES256_GCM,data:bardp/gZoPU6D6JgV3RDbrCiG49eIlCcRRZkn8KNkNXdbsWV21VQHNfrmMKwxKcqPqxhvMGqFniFKGFzPdV3EIiGHdV16gS++yUmVS/idDr8ZxEtfd4JcrgK3LBavJ56nsJKMrJX8GWshZ6dXXkg5h57rfTjgf3qfCWwXeYDG91KNcnVMyeiOuFIcy5kYnEHmYxnQ6J8XlUcH5h6LSGW2FSg83HdBVP7UBRe2/iz3paThBrXjztbzttuQM2qXg4VKLnWhj4se8EUWllfaPLtAKvjTAHbAuKVtF01QeT1HkvRUyhrq75PsFpSeMS8PFdKCewMM24l7uCtnRWIBw2IomEtdPXJtyaUmdAyhb4zjXn27uCXkG6Pi9td5IV8PHLoFdhesBPY6iwKznZmxS88tc3aMBeRhFZcukti3MP0TNABIgDigexLJCrjgL1tShVZ6A3qgv60QtOeATcnacq1OoKCh2UmGrjoREJzgRmaVHCKIyt+ih5fdMctUExbgtMhPa2cf8eB5eOizAwOHN2S18DvjbsmEOkKCl/+x+S2,iv:7y3rDrLYlr0/e0QG1WO3VpqMTby4x0tGE5PSIA8vfTA=,tag:SgMUt942cjQeqIc5/zfYCw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUktXVW5qM3Ivak8wOTNV\ndmczSnNNeVhkRlBJSERHbW5UemxTUHFSc3c4Ck9FeVJ5bURCMmg5NWw3eTdIcU5x\ndjRMNGQwckNsa0RBWE9FQmREOFlRT1UKLS0tIHp5REg5c2ZrL2tkVHBKUTNpUWJE\nNGdPWG5Zb3A2T3VRQUw3K1VFa1IyT2MKowXrRbm/Z8IZN8/AOUuCjuc3QKyTG5ZI\n0QKR5QeEBYm0Zs68MnEtQSeeuHNKDRtZhZauK6wjU+ZsZiiqrOkb3A==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-17T21:42:15Z",
		"mac": "ENC[AES256_GCM,data:RgGc8MXUanEVIrU15/SzTJYL15WbqZuf0mDA4pdZjc22YYe8IdVDIusallKfSiDZgVmTDXDx7cWiqmXElVbghiSNwjbaBzeUULnLflWa5e7iJdW4kq49fE5vlGYWLD2UjUoTdUQwH5YeXNRS5Yjsr13WTdrjWWQpN2DmUM5b+zU=,iv:OD5a6b2UvoXIl83+sNeOfLSesAPWURhELGsl9YmVOhE=,tag:8DL3LpNPms5AWkopzbVFOw==,type:str]",
		"version": "3.13.3"
	}
}
