{
	"data": "ENC[AES256_GCM,data:2Pnl9HlYiZsW4W+YJPvTVfOe5hsCv0qrz6efPqF8rsoJzNIH6pdiin7wDG5RRP8RX0hz+xiP8AjL95x88RgWvyjnmFB0Rxjd9zZ2XF5WO+3vyddefAeA8rHxru4+aDJj6+G5oGiPCvUyN0TAHJQcuFlDtpXCC+K7ob05FeNGp7hCSJmdk6p1eFOWrPBeEsSoSlmjpNT5hyUR3R5zPSLXh0ciTKMWwGF8Ng==,iv:GZaQTb5+fh9AIIzjQDJZLKRyw9qz+sjmswzd5/dm1zo=,tag:C8TPP4hgQoGaPLeP8ZyiZg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUWE4ZHBDNGFYNjlQMzZC\nNlNKQWtPdE9tdldabzdUQmJMMjI5ZVZzVURZCjZVc2dPTWtnb2tEUmlSQnF0blpu\nOFFoNGpQTGRueFZXOTJxcXRuUEtVZFEKLS0tIHI3ejVDSnZIaGltK3c1blZMZXJz\nOWFpM0hxNE1FbVZ4bzhaWU0yYUxhcGMKAq3XMYQEGZHMjWBcZOnUB6i0FLOFsPC7\na+KQcC6+YSviWgv/JvaDKcJsERR2qUaPQ57bTxPIFP8Jmwoo27k+ag==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-12T17:07:02Z",
		"mac": "ENC[AES256_GCM,data:TKfXpv8TXbQBXMiQmBHetxFEu9yiSb3jxatEbniV1ytbd5MBuZt029YijXZlg6Q0TGUmLXbg64EBhLqjijwBdG4O1b65PBq7Ffxm+n9q/FDdB52MgsePWL0nBXpuoDYmbkA2msBDyoE6zYPNaAyzqCU7W12ZYvwD5cjCg4NtRew=,iv:edl1uAPET5A96n+xmJNJqRD1bOOFi5gVcaVtTiMKr28=,tag:bR8RLDKeObaBWVwfmySxSQ==,type:str]",
		"version": "3.13.3"
	}
}
