{
	"data": "ENC[AES256_GCM,data:+1QQayTSPEddU++tPGARUNq9NQYQwZTz+IRzWudvM6G4cvZWnoPU+9NSJnGzHJddCjBZ1qsr7a9W18/3nrCG0bggOo2MKV1aphjLSEYLu+/0trzYrW1Kh73SOtxKFdkOawk8v5ykHWSZtIcDf+iLS0o86tMM5MMfS4kR3ZlS58QtaRD//DjVXEj+C4pEYQ9pGQJ5rfXTlJAxFJ8yQa2E8pRINo2HDHwd6Hb74pRQrQ3lAjX+SYaM4oZRZWB3qJ96wkVMH537j7EczI9IMFmr2Ol+3zmrRSPuCAg5qwlyJFE22XYte/XoAbIApatm6S9Qdv72ecyX5Qfmk+cmsLnN/T13tSdoGlUmrT6G0OlyZQbnlAKUeySJrb8SAGI8KQfKnQjxzJSGPeg4Q+K0QnLfR1FS/u52OIcege8vweW2BoooMAzkMgBm2cYeBjMtB5dS/WKKVWTqFxL7CZlU9a2FWXJv6HFT1YfxXJK6V8yjSRGHmfLOiPFJKZsN+SOnaE6W3k0XCNJ6bQQ30Aj0BG1r0A==,iv:YLKo55wJO8TJ+WEzcDlkJDyD4qfERDSp8xTmBQ0CitE=,tag:VKe6zXa5VPcvPMkdX9CuZw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWVpCTUtldGNabG1TZDlX\nREV2UDBQaDhBa2FNbmphWlFmdkZ1M1RjdkI0CnV3c0RwVzBIRHMzeU51YVhWdHdk\nR3M1cEpiNTBpMDl0bHZDVEdTdUVOS1kKLS0tIEhvMnhNeTZYKzhSRDBKV2RGVE5i\nR3VFUnVjM1lDVEFyVDh2N25OcXhIL3MKeuG+Y6tO8Xaqwpk6XnkeIVobONmoVXr0\nZaESmoEiM/oGesoTeM4SgQHbGtVY5Q+SlB8bBERkRzjRRobWhntpqg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age15q0jchsjm6dzwqs78fwgegm3zlsu7pc0d6ul02aatdyxrq9cnudsqzcrwq"
			}
		],
		"lastmodified": "2026-09-12T17:07:02Z",
		"mac": "ENC[AES256_GCM,data:/rKFLHuhynEZtnnuPp3xIWuaBVK1YsKbXlLqbmESY9z1o69vjMdhA82TCsydMMdsBj7VFMtPUoMcpsniSa+tRj2Ku+ts2FvUrZ+qmXF8a1QyoTWFAs7s7+amuxu5TdT6LWqAaPY58vBN8YtwctjwYPNOKZT8bodOdG5T9bUERv4=,iv:zBu7IldFpdhrnqa9snqU67fd/S1orpG7NCqiaSSEa00=,tag:RjA4JZv2eJB1vCka3gNpTg==,type:str]",
		"version": "3.13.3"
	}
}
