name: CyberHam

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: cyberham-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cyberham:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt secrets
        run: decrypt cyberham

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.3"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Lint repo
        run: uv run ruff check --output-format=github

      - name: Check formatting
        run: uv run ruff format --check --diff

      - name: Typecheck repo
        run: uv run pyright --level error

      - name: Run tests
        env:
          CYBERHAM_ENV: dev
        run: uv run python -m pytest

      - name: Build image
        run: docker build --pull -t $REGISTRY_URI/cyberham:${{ github.sha }} .

      # - name: Scan image
      #   run: scan $REGISTRY_URI/cyberham:${{ github.sha }} 

      - name: Tag image
        if: github.event_name == 'push'
        run: |
          docker tag \
            $REGISTRY_URI/cyberham:${{ github.sha }} \
            $REGISTRY_URI/cyberham:latest

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push $REGISTRY_URI/cyberham:${{ github.sha }}
          docker push $REGISTRY_URI/cyberham:latest

      - name: Deploy image
        if: github.event_name == 'push'
        run: docker compose pull && docker compose up -d
